start_directory: ~/dev/projects/startpage
session_name: startpage
windows:
  - window_name: editor
    panes:
      - shell_command:
          - nvim
  - window_name: tasks
    panes:
      - shell_command:
          - nvim
  - window_name: git
    panes:
      - shell_command:
          - lazygit
  - window_name: notes
    start_directory: ~/documents/obsidian-vaults/personal
    panes:
      - null
